# Header
menu:
  Home: /
  About: /about
  Our Team: /our-team
  Summer Camp: /courses/summer-camp
  Courses: 
    url: /courses
    children:
      Robotics: 
        url: /robotics
        avatar: /css/images/robotic-avatar.png
        descriptions: 
          - "<b>Quick progress</b>: Fast-forward through theory and participate in high-standard competitions"
          - "<b>Programming skill</b>: Learn from expert teachers in Robotics"
          - "<b>Ample support</b>: Get enough and extra materials for projects"
        highlights:
          - "DesA"
          - "DesB"
      Coding: 
        url: /coding
        avatar: /css/images/coding-avatar.png
        descriptions:
          - "<b>Personalized learning</b>: Customized curriculum and goals"
          - "<b>Practical projects</b>: Learn by doing a lot of hand-on projects"
          - "<b>Quality syllabus</b>: Customized from renowned experts"
          - "<b>Expert instructors</b>: Highly qualified faculty with master's degrees or higher"
      # Digital Art: 
      #   url: /digital-art
      #   avatar: /css/images/digital-art-avatar.png
      #   descriptions:
      #     - "Acquire proficiency in employing a wide array of digital tools and techniques essential for digital art creation"
      #     - "Explore diverse avenues of creative expression within the digital realm"
      Mentorship: 
        url: /mentorship
        avatar: gallery/standford.webp
        descriptions:
          - "<b>Parents' allies</b>: Peace of mind and long-term expert support"
          - "<b>Expert instructors</b>: Highly qualified faculty with master's degrees or higher"
          - "<b>University prep</b>: Standout your portfolio and skills"
          - "<b>STEM exploration</b>: Career advice from specialists"
  Gallery: /gallery
  News: /news
  Contact: /contact

title: Happy Kids Education

advantages:
  STEM CAREER PLANNING: Planning your STEM career with our experts
  PARENTAL PARTNERSHIP: Accompanying with parents to enhance learning and growth
  CUSTOMIZED TASKS: Providing personalized tasks and resources in all areas
  NEXT-LEVEL GROWTH: Helping your kid boost their skill and confidence, and surpass their expectations
  HOLISTIC DEVELOPMENT: Tailoring hands-on learning environment to fully boost curiosity, innovation and problem-solving
  CLEAR CAREER PATH: Helping students explore their professional choices and plan their career goals

rss: /atom.xml
banner: "images/banner.jpg"

# Content
excerpt_link: Read More
fancybox: true

# # Footer
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Footer
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use html like below...
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# Widget behavior
archive_type: 'monthly'
show_count: false
recent_posts_limits: 5

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: data/favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
